### ISSUE TITLE
ImportWrapper fails on the Wouters data

### ISSUE THREAD

**Issue by morungos** [pughlab/cbioportal#23]
Stack backtrace is:

```
java.io.FileNotFoundException: meta_mutation_extended.txt (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileInputStream.<init>(FileInputStream.java:101)
	at java.io.FileReader.<init>(FileReader.java:58)
	at org.mskcc.cbio.portal.MetaFileReader.metaReader(MetaFileReader.java:20)
	at org.mskcc.cbio.portal.XMLWriter.buildXML(XMLWriter.java:68)
	at org.mskcc.cbio.portal.ImportWrapper.main(ImportWrapper.java:78)
Exception in thread "main" java.lang.NullPointerException
	at org.mskcc.cbio.portal.XMLWriter.buildXML(XMLWriter.java:73)
	at org.mskcc.cbio.portal.ImportWrapper.main(ImportWrapper.java:78)
```

Command line was (on Samwise):

```
java -cp scripts-1.0-SNAPSHOT.jar org.mskcc.cbio.portal.ImportWrapper /home/cbioportal/Wouters applicationContext-dao.xml
```

**Comment by morungos** [comment]
Seems to run OK when run within `/home/cbioportal/Wouters`, so it's expecting a specific working directory and it shouldn't.
