### ISSUE TITLE
Error importing the brca study sample data

### ISSUE THREAD

**Issue by morungos** [pughlab/cbioportal#25]
Command used:

```
ava -cp /home/cbioportal/local/scripts-1.0-SNAPSHOT.jar org.mskcc.cbio.portal.ImportWrapper /home/cbioportal/software/brca-study /home/cbioportal/local/applicationContext-dao.xml
```

We get a deep SQL error in the backtrace

```
Percentage Complete:  ∞%
Mem Allocated:  2,476 MB, Mem used:  217.443 MB, Mem free:  2,258.557 MB
..........
Percentage Complete:  ∞%
Mem Allocated:  2,476 MB, Mem used:  318.013 MB, Mem free:  2,157.987 MB
..........
Percentage Complete:  ∞%
Mem Allocated:  2,476 MB, Mem used:  398.471 MB, Mem free:  2,077.529 MB
...Success!
java.io.FileNotFoundException: /home/cbioportal/software/brca-study/meta_clinical.txt (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileInputStream.<init>(FileInputStream.java:101)
	at java.io.FileReader.<init>(FileReader.java:58)
	at org.mskcc.cbio.portal.MetaFileReader.metaReader(MetaFileReader.java:20)
	at org.mskcc.cbio.portal.scripts.ImportMethylation.main(ImportMethylation.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mskcc.cbio.portal.util.TransactionalScripts.run(TransactionalScripts.java:52)
	at org.mskcc.cbio.portal.scripts.TransactionalScriptRunner$1.doInTransaction(TransactionalScriptRunner.java:97)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.mskcc.cbio.portal.scripts.TransactionalScriptRunner.runInTransaction(TransactionalScriptRunner.java:94)
	at org.mskcc.cbio.portal.scripts.TransactionalScriptRunner.run(TransactionalScriptRunner.java:79)
	at org.mskcc.cbio.portal.scripts.TransactionalScriptRunner.main(TransactionalScriptRunner.java:45)
	at org.mskcc.cbio.portal.ImportWrapper.main(ImportWrapper.java:84)
org.apache.commons.lang.exception.NestableRuntimeException: Can't call main method in: org.mskcc.cbio.portal.scripts.ImportMethylation
	at org.mskcc.cbio.portal.util.TransactionalScripts.run(TransactionalScripts.java:65)
	at org.mskcc.cbio.portal.scripts.TransactionalScriptRunner$1.doInTransaction(TransactionalScriptRunner.java:97)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.mskcc.cbio.portal.scripts.TransactionalScriptRunner.runInTransaction(TransactionalScriptRunner.java:94)
	at org.mskcc.cbio.portal.scripts.TransactionalScriptRunner.run(TransactionalScriptRunner.java:79)
	at org.mskcc.cbio.portal.scripts.TransactionalScriptRunner.main(TransactionalScriptRunner.java:45)
	at org.mskcc.cbio.portal.ImportWrapper.main(ImportWrapper.java:84)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mskcc.cbio.portal.util.TransactionalScripts.run(TransactionalScripts.java:52)
	... 6 more
Caused by: org.mskcc.cbio.portal.dao.DaoException: Duplicate entry 'brca_tcga_pub_methylation_hm27' for key 'STABLE_ID'
	at org.mskcc.cbio.portal.dao.DaoGeneticProfile.addGeneticProfile(DaoGeneticProfile.java:120)
	at org.mskcc.cbio.portal.scripts.ImportMethylation.main(ImportMethylation.java:44)
	... 11 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'brca_tcga_pub_methylation_hm27' for key 'STABLE_ID'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2625)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2119)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2415)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2333)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2318)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.mskcc.cbio.portal.dao.DaoGeneticProfile.addGeneticProfile(DaoGeneticProfile.java:118)
	... 12 more
```

**Comment by morungos** [comment]
Bad data
