### ISSUE TITLE
Apparent connection timeout problem

### ISSUE THREAD

**Issue by morungos** [pughlab/cbioportal#32]
I've just noticed we got some errors from the portal, which seemed transient but I think it's the old MySQL connection-dropping problem. Backtrace:

If I remember, there are data source options that can be used to keep the MySQL connections alive. These need to be added to the Jetty cbioportal.xml file for production use. 

We should test to see if this is a problem, typically by leaving the server alone for an hour or so, and then seeing what happens when we first try to reconnect. 

```
The last packet successfully received from the server was 7,709,266 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3090)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2979)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3520)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2625)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2119)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2281)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.mskcc.cbio.portal.dao.DaoPatientList.getPatientListByStableId(DaoPatientList.java:87)
	... 60 more
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2540)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2990)
	... 70 more
[WARNING] ServletHandler:
org.apache.jasper.JasperException: An exception occurred processing JSP page /data_sets.jsp at line 93
```

**Comment by morungos** [comment]
First, we never put this in production, which was something of an error, and second, it's not clear that it's enough. I think we need to look into the eviction system for the pool too, and maybe even auto_reconnect.

**Comment by morungos** [comment]
I've deployed these changes in the tracker-server configuration, and after 1.5 hours everything smoothly started. So I'm closing this as resolved.
