### ISSUE TITLE
NullPointerException in MutationDataUtils#getMutationData

### ISSUE THREAD

**Issue by morungos** [pughlab/cbioportal#34]
Backtrace: 

```
2015-07-20 15:52:48 [qtp1421559611-27] DEBUG org.mskcc.cbio.portal.util.internal.AccessControlImpl - getCancerStudies(), getting accessible cancer studies.
2015-07-20 15:52:48 [qtp1421559611-25] DEBUG org.mskcc.cbio.portal.util.internal.AccessControlImpl - hasPermission(), stableStudyId: lts_ov_oza
[WARNING] ServletHandler: /getMutationData.json
java.lang.NullPointerException
	at org.mskcc.cbio.portal.util.MutationDataUtils.getMutationData(MutationDataUtils.java:128)
	at org.mskcc.cbio.portal.servlet.MutationDataServlet.doPost(MutationDataServlet.java:99)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.mskcc.cbio.portal.util.XssFilter.doFilter(XssFilter.java:65)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
```

**Comment by jgsong95** [comment]
Note that all stable ids for mutation_extended data is expected to have suffix "_mutations"
Changed servlet to throw 404 if genetic profile is null

**Comment by jgsong95** [comment]
impact/compact data had incorrect patient ids (PMH111-111 instead of IMP111-1111/COM111-1111) - re imported wrong data and error popped up again

**Comment by morungos** [comment]
Interesting... Yes, that's something that should not get to the front end. Can we handle that as an error in the import?

**Comment by jgsong95** [comment]
fixed
