### ISSUE TITLE
Error in OpenID Connect with Google authentication

### ISSUE THREAD

**Issue by morungos** [pughlab/cbioportal#46]
I'm now getting a new error from OpenID Connect. it's possible this is from an upstream merge.

```
java.lang.ClassCastException: com.google.common.collect.RegularImmutableMap cannot be cast to org.springframework.security.core.userdetails.User
	at org.mskcc.cbio.portal.util.CancerStudyPermissionEvaluator.hasPermission(CancerStudyPermissionEvaluator.java:104)
	at org.springframework.security.access.expression.SecurityExpressionRoot.hasPermission(SecurityExpressionRoot.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by morungos** [comment]
Yes, I see the problem at https://github.com/pughlab/cbioportal/blob/develop/authentication/src/main/java/org/mskcc/cbio/portal/util/CancerStudyPermissionEvaluator.java#L104. There's really no way that we can assume the Principal is a User when it's come from a different authentication component, is there?
